CREATE DATABASE taxi_motos;
USE taxi_motos;

CREATE TABLE usuarios(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(70) NOT NULL UNIQUE KEY,
    correo VARCHAR(70) NOT NULL UNIQUE KEY,
    contra VARCHAR(70) NOT NULL,
    tel VARCHAR(10) NOT NULL UNIQUE KEY,
    edad INT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB;
CREATE TABLE taxista(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(70) NOT NULL UNIQUE KEY,
    num_taxi VARCHAR(20) NOT NULL UNIQUE KEY,
    tel VARCHAR(10) NOT NULL UNIQUE KEY,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE = InnoDB;
CREATE TABLE pedido(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_usuario INT NOT NULL,
    id_taxista INT NOT NULL,
    origen VARCHAR(150) NOT NULL,
    destino VARCHAR(150) NOT NULL,
    estado VARCHAR(20) NOT NULL, 
    fecha_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id),
    FOREIGN KEY (id_taxista) REFERENCES taxista(id)
)ENGINE = InnoDB;
CREATE TABLE pago(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_pedido INT NOT NULL,
    cantidad INT NOT NULL,
    pago_realizado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_pedido) REFERENCES pedido(id)
)ENGINE = InnoDB;



